.env.example
.github/workflows/docker-build.yml
.github/workflows/image-smoke.yml
.github/workflows/publish_release.yml
.github/workflows/release.yml
Dockerfile
README.md
README_APPROVAL.md
README_DEPLOY.md
config.runtime.test.json
config_loader.py
deploy/systemd/docker-compose-app.service
deploy/systemd/telegram-webhook.service
docker-compose.override.yml
docker-compose.yml
entrypoint.sh
freqtrade-backtest-captured.log
freqtrade-logs/backtesting-bybit-datadir.log
freqtrade-logs/backtesting-range-2.log
freqtrade-logs/backtesting.log
freqtrade-logs/download-data.log
get_telegram_ids.py
pip_install.log
requirements.txt
scripts/check_ml.py
scripts/check_wsl.ps1
scripts/docker_precheck.ps1
scripts/download_history.ps1
scripts/install_freqai.ps1
scripts/install_pip.ps1
scripts/migrate_secrets.ps1
scripts/run_backtest.ps1
scripts/run_backtest_docker.ps1
strategies/ml_grid_strategy.py
telegram_publisher_bot.py
telegram_publisher_webhook.py
tests/test_custom_stoploss.py
tools/parse_backtest_debug.py
tools/threshold_scan.py
user_data/backtest_results/.last_result.json
user_data/backtest_results/backtest-result-2025-10-07_20-20-08.meta.json
user_data/backtest_results/backtest-result-2025-10-07_20-20-08.zip
user_data/data/bybit/BTC-USDT-1h.csv
user_data/data/bybit/BTC_USDT-1h.feather
user_data/hyperopts/sample_hyperopt_loss.py
user_data/notebooks/strategy_analysis_example.ipynb
user_data/strategies/ml_grid_strategy.py
user_data/strategies/sample_strategy.py
